import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Image from "next/image";

const inter = Inter({ subsets: ['latin'] })

const myLoader = ({ src }) => {
    return `https://www-league.nhlstatic.com/images/logos/league-dark/${src}.svg`
}

export default function Home() {
  return (
    <>
        <Head>
            <title>NHL Data Project</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.center}>
            <Image
                loader={myLoader}
                src="133-flat"
                alt="The NHL Logo"
                width={250}
                height={250}
            />
        </div>

        <div className={styles.gridLanding}>
            <Link
                href="/teams/"
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
            >
                <h2 className={inter.className}>
                    Team Info <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    Find in-depth information about all current NHL Teams
                </p>
            </Link>

            <a
                href="/"
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
            >
                <h2 className={inter.className}>
                    Players Info <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    Find all the information about players here!
                    --- NOT CURRENTLY ACTIVE ---
                </p>
            </a>
        </div>
    </>
  )
}
